/*
 * LANGUAGE CONTEXT — Sweeptakes.com
 * Bilingual support: English (en) + Spanish (es)
 * For the US Latino audience
 * Full coverage: Navbar, Hero, Auth, BonusTicker, WhatAre, TopCasinos,
 *   HowWeRank, FeaturedReview, BonusGuide, LegalStates, TrustSection, FAQ, Footer
 */
import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "es";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // ── Navbar ──────────────────────────────────────────────────────────────
    "nav.topCasinos": "Top Casinos",
    "nav.howItWorks": "How It Works",
    "nav.bonuses": "Bonuses",
    "nav.legalStates": "Legal & States",
    "nav.reviews": "Reviews",
    "nav.exploreCasinos": "Explore Casinos",
    "nav.login": "Log In",
    "nav.signup": "Sign Up Free",
    "nav.logout": "Log Out",
    "nav.myAccount": "My Account",
    "nav.welcome": "Welcome back",

    // ── Hero ─────────────────────────────────────────────────────────────────
    "hero.badge1": "#1 Trusted Authority 2026",
    "hero.badge2": "100% Legal USA",
    "hero.mrSweepsSays": "Mr. Sweeps: \"I've tested every casino so you don't have to. Here are the REAL winners!\"",
    "hero.title1": "Best Sweepstakes",
    "hero.title2": "Casinos USA",
    "hero.year": "2026",
    "hero.subtitle": "Play legally. Claim bonuses. Redeem real rewards.",
    "hero.noDeposit": "No deposit required",
    "hero.noDepositSuffix": " to start.",
    "hero.trust1": "Expert-reviewed casinos",
    "hero.trust2": "Updated daily",
    "hero.trust3": "Legal in 45+ states",
    "hero.cta1": "Explore Top Casinos",
    "hero.cta2": "How It Works",
    "hero.stat1": "Reviewed Casinos",
    "hero.stat2": "Legal States",
    "hero.stat3": "Free to Play",

    // ── Auth Modal ────────────────────────────────────────────────────────────
    "auth.loginTitle": "Welcome Back!",
    "auth.loginSubtitle": "Log in to save your favorite casinos and track bonuses.",
    "auth.signupTitle": "Join Sweeptakes.com",
    "auth.signupSubtitle": "Create your free account and start tracking the best bonuses.",
    "auth.loginWith": "Continue with Manus",
    "auth.orEmail": "or continue with email",
    "auth.email": "Email address",
    "auth.password": "Password",
    "auth.name": "Full name",
    "auth.loginBtn": "Log In",
    "auth.signupBtn": "Create Free Account",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.signupLink": "Sign up free",
    "auth.loginLink": "Log in",
    "auth.forgotPassword": "Forgot password?",
    "auth.terms": "By creating an account you agree to our",
    "auth.termsLink": "Terms of Service",
    "auth.and": "and",
    "auth.privacyLink": "Privacy Policy",
    "auth.loggedInAs": "Logged in as",
    "auth.logoutConfirm": "You have been logged out.",

    // ── Bonus Ticker ──────────────────────────────────────────────────────────
    "ticker.label": "🔥 Today's Bonuses",
    "ticker.item1": "🎰 Stake.us — 250K Gold Coins + 1 SC FREE",
    "ticker.item2": "⚡ RealPrize — 10,000 Gold Coins No Deposit",
    "ticker.item3": "👑 Crown Coins — 1,000 CC + 10 SC Welcome Bonus",
    "ticker.item4": "🎯 McLuck — 7,500 GC + 2.5 SC for New Players",
    "ticker.item5": "🌟 WOW Vegas — 1.75 SC + 35 WOW Coins Free",
    "ticker.item6": "🤠 LoneStar — 5,000 Gold Coins on Sign Up",
    "ticker.item7": "💰 Fortuna — 500 FC + 5 SC Welcome Package",
    "ticker.item8": "🎪 Hello Millions — 2M Hello Coins + 2 SC",

    // ── What Are Sweepstakes Casinos ──────────────────────────────────────────
    "what.badge": "Mr. Sweeps Explains",
    "what.title1": "What Are Sweepstakes",
    "what.title2": "Casinos?",
    "what.desc": "Sweepstakes casinos are a unique, legal form of online gaming available across most of the United States. Unlike traditional online casinos, they operate under sweepstakes law — meaning you can play casino-style games for free and still win real prizes.",
    "what.f1title": "Two-Currency System",
    "what.f1desc": "Play with Gold Coins (fun) or Sweep Coins (redeemable). You never have to buy anything.",
    "what.f2title": "100% Legal in the USA",
    "what.f2desc": "Sweepstakes casinos operate under federal sweepstakes law — no gambling license required.",
    "what.f3title": "Free Entry Always Available",
    "what.f3desc": "By law, you can always request free Sweep Coins by mail. No purchase necessary.",
    "what.f4title": "Redeem for Real Prizes",
    "what.f4desc": "Accumulated Sweep Coins can be redeemed for cash prizes, gift cards, or crypto.",
    "what.step1": "Sign up for free — no credit card needed",
    "what.step2": "Receive free Sweep Coins on registration",
    "what.step3": "Play slots, table games, and more",
    "what.step4": "Redeem Sweep Coins for real cash prizes",

    // ── Top Casinos ───────────────────────────────────────────────────────────
    "casinos.badge": "Expert Ranked 2026",
    "casinos.title1": "Top Ranked Sweepstakes",
    "casinos.title2": "Casinos USA",
    "casinos.desc": "Every casino below has been personally tested, verified for legality, and ranked by our editorial team.",
    "casinos.mrSweeps": "\"These are my personal top picks — I've played them all!\"",
    "casinos.readReview": "Read Full Review",
    "casinos.viewAll": "View All 11 Casinos",
    // Casino taglines
    "casino.stake.tagline": "Best Overall Sweepstakes Casino",
    "casino.stake.badge": "Editor's Choice",
    "casino.stake.pro1": "Huge game library (800+)",
    "casino.stake.pro2": "Daily login bonuses",
    "casino.stake.pro3": "Fast redemptions",
    "casino.realprice.tagline": "Best for Slots & Variety",
    "casino.realprice.badge": "Top Rated",
    "casino.realprice.pro1": "Exclusive slot titles",
    "casino.realprice.pro2": "No purchase necessary",
    "casino.realprice.pro3": "Mobile-friendly",
    "casino.crown.tagline": "Best Welcome Bonus",
    "casino.crown.badge": "Best Bonus",
    "casino.crown.pro1": "Generous welcome offer",
    "casino.crown.pro2": "Live dealer games",
    "casino.crown.pro3": "24/7 support",
    "casino.mcluck.tagline": "Best for New Players",
    "casino.mcluck.badge": "Beginner Pick",
    "casino.mcluck.pro1": "Easy registration",
    "casino.mcluck.pro2": "No KYC for small prizes",
    "casino.mcluck.pro3": "Great mobile app",
    "casino.wow.tagline": "Best Social Casino Experience",
    "casino.wow.badge": "Popular",
    "casino.wow.pro1": "Vegas-style atmosphere",
    "casino.wow.pro2": "Tournaments available",
    "casino.wow.pro3": "Instant play",
    "casino.lonestar.tagline": "Best for Texas Players",
    "casino.lonestar.badge": "Regional Pick",
    "casino.lonestar.pro1": "Texas Hold'em focus",
    "casino.lonestar.pro2": "State-specific offers",
    "casino.lonestar.pro3": "Poker tournaments",
    "casino.fortuna.tagline": "Best Redemption Process",
    "casino.fortuna.badge": "Fast Pay",
    "casino.fortuna.pro1": "Fast cash redemptions",
    "casino.fortuna.pro2": "Multiple payment methods",
    "casino.fortuna.pro3": "Transparent terms",
    "casino.hello.tagline": "Best for Progressive Jackpots",
    "casino.hello.badge": "Jackpot King",
    "casino.hello.pro1": "Massive jackpot pools",
    "casino.hello.pro2": "Daily free coins",
    "casino.hello.pro3": "Loyalty rewards",
    "casino.spree.tagline": "Best Mobile Sweepstakes",
    "casino.spree.badge": "Mobile Best",
    "casino.spree.pro1": "Native iOS & Android app",
    "casino.spree.pro2": "Smooth gameplay",
    "casino.spree.pro3": "Quick sign-up",
    "casino.funrize.tagline": "Best for Casual Players",
    "casino.funrize.badge": "Casual Pick",
    "casino.funrize.pro1": "No pressure gameplay",
    "casino.funrize.pro2": "Casual-friendly UI",
    "casino.funrize.pro3": "Fun tournaments",
    "casino.mega.tagline": "Best Bonus Frequency",
    "casino.mega.badge": "Bonus King",
    "casino.mega.pro1": "Hourly bonus drops",
    "casino.mega.pro2": "Referral rewards",
    "casino.mega.pro3": "VIP program",

    // ── How We Rank ───────────────────────────────────────────────────────────
    "rank.badge": "Our Methodology",
    "rank.title1": "How We",
    "rank.title2": "Rank",
    "rank.title3": "Casinos",
    "rank.desc": "Our editorial team applies a rigorous, transparent scoring system. Every casino is tested hands-on before receiving a rating.",
    "rank.c1title": "Legal Compliance",
    "rank.c1desc": "We verify every casino operates under valid sweepstakes law and is accessible in your state.",
    "rank.c2title": "Bonus Value",
    "rank.c2desc": "We evaluate welcome offers, daily bonuses, and the real value of free Sweep Coins.",
    "rank.c3title": "Game Selection",
    "rank.c3desc": "Quality and quantity of slots, table games, live dealer, and specialty games.",
    "rank.c4title": "Redemption Speed",
    "rank.c4desc": "How fast and easy it is to convert Sweep Coins into real cash prizes.",
    "rank.c5title": "User Experience",
    "rank.c5desc": "Mobile performance, site speed, registration process, and customer support quality.",
    "rank.c6title": "Ongoing Updates",
    "rank.c6desc": "We re-test and update every review monthly to ensure accuracy.",
    "rank.promiseTitle": "Our Editorial Promise",
    "rank.promiseDesc": "Sweeptakes.com operates independently. We are not owned by any casino operator. Our rankings are based solely on editorial merit — we may earn affiliate commissions, but this never influences our scores or recommendations.",

    // ── Featured Review (Stake.us) ────────────────────────────────────────────
    "review.badge": "Featured Review",
    "review.title": "Stake.us Review",
    "review.updated": "Last updated: February 2026 · Reviewed by James Hartley",
    "review.editorsChoice": "Editor's Choice",
    "review.overallScore": "Overall Score",
    "review.prosLabel": "✓ Pros",
    "review.consLabel": "✗ Cons",
    "review.bonusBreakdown": "🎁 Bonus Breakdown",
    "review.bonusWelcome": "Welcome Bonus",
    "review.bonusDaily": "Daily Bonus",
    "review.bonusReferral": "Referral Bonus",
    "review.scoreGame": "Game Selection",
    "review.scoreBonus": "Bonus Value",
    "review.scoreRedemption": "Redemption",
    "review.scoreMobile": "Mobile",
    "review.scoreSupport": "Support",
    "review.scoreLegal": "Legal",
    "review.pro1": "Largest game library (800+ titles)",
    "review.pro2": "Daily login bonuses and promotions",
    "review.pro3": "Fast and reliable redemptions",
    "review.pro4": "Excellent mobile experience",
    "review.pro5": "Transparent terms and conditions",
    "review.pro6": "24/7 customer support",
    "review.con1": "Not available in Washington state",
    "review.con2": "Redemption minimum of $100",
    "review.con3": "No dedicated poker room",
    "review.bonusWelcomeVal": "250,000 Gold Coins + 1 Sweep Coin",
    "review.bonusDailyVal": "Daily login bonus up to 10,000 GC",
    "review.bonusReferralVal": "Earn 1 SC per referral",
    "review.ctaRead": "Read Full Review",
    "review.ctaVisit": "Visit Stake.us",

    // ── Bonus Guide ───────────────────────────────────────────────────────────
    "bonus.badge": "Free Coins Guide",
    "bonus.title1": "Bonuses &",
    "bonus.title2": "Free Coins",
    "bonus.desc": "Every sweepstakes casino offers multiple ways to earn free Sweep Coins. Here's everything you need to know to maximize your rewards.",
    "bonus.mrSweepsTip": "\"You can ALWAYS get free Sweep Coins — even without spending a dime. That's the beauty of sweepstakes!\"",
    "bonus.proTipLabel": "Mr. Sweeps' Pro Tip",
    "bonus.proTip": "Sign up for multiple sweepstakes casinos to maximize your free coin collection. Each platform offers its own welcome bonus, and since they're all free to join, there's no reason not to claim them all!",
    "bonus.viewTop": "View Top Casinos",
    "bonus.b1title": "Welcome Bonus",
    "bonus.b1desc": "Get free Gold Coins and Sweep Coins just for signing up. No deposit required.",
    "bonus.b1value": "Up to 250K GC + 10 SC",
    "bonus.b2title": "Daily Login Bonus",
    "bonus.b2desc": "Log in every day to claim free coins. The longer your streak, the bigger the reward.",
    "bonus.b2value": "Daily free coins",
    "bonus.b3title": "Free Mail Entry",
    "bonus.b3desc": "By law, you can always request free Sweep Coins by mailing a handwritten request.",
    "bonus.b3value": "Always free by law",
    "bonus.b4title": "VIP & Loyalty Rewards",
    "bonus.b4desc": "Earn loyalty points as you play. Higher tiers unlock exclusive bonuses and faster redemptions.",
    "bonus.b4value": "Exclusive perks",
    "bonus.b5title": "Reload Bonuses",
    "bonus.b5desc": "Purchase Gold Coin packages and receive bonus Sweep Coins on top — optional, never required.",
    "bonus.b5value": "Bonus SC on purchases",
    "bonus.b6title": "Referral Bonuses",
    "bonus.b6desc": "Invite friends and earn free coins when they sign up and play.",
    "bonus.b6value": "Earn per referral",

    // ── Legal & States ────────────────────────────────────────────────────────
    "legal.badge": "State Availability",
    "legal.title1": "Legal &",
    "legal.title2": "State",
    "legal.title3": "Availability",
    "legal.desc": "Sweepstakes casinos are legal in most U.S. states. Here's what you need to know about your state.",
    "legal.whyLegal": "Why It's Legal",
    "legal.l1title": "Federal Sweepstakes Law",
    "legal.l1desc": "Sweepstakes casinos operate under 18 U.S.C. § 1302 and state sweepstakes statutes, not gambling law.",
    "legal.l2title": "No Purchase Necessary",
    "legal.l2desc": "The cornerstone of legality: free entry must always be available. This is enforced by all operators.",
    "legal.l3title": "State Variations",
    "legal.l3desc": "A few states have additional restrictions. Always check your state's specific rules before playing.",
    "legal.legendTitle": "Status Legend",
    "legal.legendAvailable": "Available — Play freely",
    "legal.legendRestricted": "Restricted — Some casinos only",
    "legal.legendUnavailable": "Unavailable — Check local laws",
    "legal.statesTitle": "State Availability",
    "legal.statesCount": "States Available",
    "legal.disclaimer": "* State availability may vary by operator. Always verify with the specific casino before playing. This information is updated regularly but is not legal advice.",

    // ── Trust Section ─────────────────────────────────────────────────────────
    "trust.stat1label": "Casinos Reviewed",
    "trust.stat2label": "Industry Experience",
    "trust.stat3label": "Monthly Readers",
    "trust.stat4label": "Editorial Independence",
    "trust.teamBadge": "Our Team",
    "trust.teamTitle1": "Meet the",
    "trust.teamTitle2": "Editorial",
    "trust.teamTitle3": "Team",
    "trust.jh.role": "Lead Casino Analyst",
    "trust.jh.bio": "10+ years reviewing online casinos and sweepstakes platforms across the US.",
    "trust.sc.role": "Legal & Compliance Editor",
    "trust.sc.bio": "Former gaming attorney specializing in sweepstakes law and state regulations.",
    "trust.mr.role": "Bonus & Promotions Specialist",
    "trust.mr.bio": "Dedicated to finding and verifying the best bonus offers across all platforms.",
    "trust.ctaTitle1": "Ready to Find Your",
    "trust.ctaTitle2": "Perfect Casino?",
    "trust.ctaDesc": "Mr. Sweeps has done all the research. Browse our top-ranked sweepstakes casinos and start playing for free today — no deposit required.",
    "trust.ctaBtn": "View Top Casinos",

    // ── FAQ ───────────────────────────────────────────────────────────────────
    "faq.badge": "Common Questions",
    "faq.title1": "Frequently Asked",
    "faq.title2": "Questions",
    "faq.mrSweeps": "\"Got questions? I've got answers! Here's everything you need to know.\"",
    "faq.cta": "Explore Top Casinos Now",

    // ── Footer ────────────────────────────────────────────────────────────────
    "footer.tagline": "The trusted guide to legal sweepstakes casinos in the United States.",
    "footer.editorial": "Editorial Independence Guaranteed",
    "footer.col1": "Top Casinos",
    "footer.col1.l1": "Stake.us Review",
    "footer.col1.l2": "RealPrize Review",
    "footer.col1.l3": "Crown Coins Review",
    "footer.col1.l4": "McLuck Review",
    "footer.col1.l5": "WOW Vegas Review",
    "footer.col1.l6": "All Casino Reviews",
    "footer.col2": "Guides",
    "footer.col2.l1": "What Are Sweepstakes Casinos?",
    "footer.col2.l2": "How to Claim Free Coins",
    "footer.col2.l3": "Redemption Guide",
    "footer.col2.l4": "Bonuses & Promotions",
    "footer.col2.l5": "Responsible Play",
    "footer.col3": "Legal",
    "footer.col3.l1": "State Availability",
    "footer.col3.l2": "Legal Disclaimer",
    "footer.col3.l3": "Editorial Policy",
    "footer.col3.l4": "Privacy Policy",
    "footer.col3.l5": "Terms of Service",
    "footer.col3.l6": "Contact Us",
    "footer.col4": "About",
    "footer.col4.l1": "About Sweeptakes.com",
    "footer.col4.l2": "Our Editorial Team",
    "footer.col4.l3": "How We Rank Casinos",
    "footer.col4.l4": "Advertise With Us",
    "footer.col4.l5": "Sitemap",
    "footer.responsible": "Responsible Play",
    "footer.responsibleDesc": "Sweepstakes casinos are for entertainment purposes only. If you feel your play is becoming problematic, visit",
    "footer.responsibleLink": "NCPG",
    "footer.responsibleSuffix": "or call 1-800-522-4700 for free, confidential support.",
    "footer.responsibleBtn": "Learn More",
    "footer.disclaimer": "Legal Disclaimer: Sweeptakes.com is an independent editorial website. We are not a casino operator and do not offer any gambling services. The information on this site is for informational purposes only. Sweepstakes casinos are legal in most U.S. states under federal sweepstakes law. We may receive compensation from casino operators when you click links on our site, but this does not influence our editorial ratings or recommendations. Always verify the legal status of sweepstakes gaming in your jurisdiction before participating. You must be 18+ to play at sweepstakes casinos.",
    "footer.copyright": "© 2026 Sweeptakes.com. All rights reserved. Not affiliated with any casino operator.",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.cookies": "Cookies",
    "footer.sitemap": "Sitemap",
  },

  es: {
    // ── Navbar ──────────────────────────────────────────────────────────────
    "nav.topCasinos": "Mejores Casinos",
    "nav.howItWorks": "Cómo Funciona",
    "nav.bonuses": "Bonos",
    "nav.legalStates": "Legal & Estados",
    "nav.reviews": "Reseñas",
    "nav.exploreCasinos": "Ver Casinos",
    "nav.login": "Iniciar Sesión",
    "nav.signup": "Regístrate Gratis",
    "nav.logout": "Cerrar Sesión",
    "nav.myAccount": "Mi Cuenta",
    "nav.welcome": "Bienvenido de vuelta",

    // ── Hero ─────────────────────────────────────────────────────────────────
    "hero.badge1": "#1 Autoridad de Confianza 2026",
    "hero.badge2": "100% Legal en EE.UU.",
    "hero.mrSweepsSays": "Mr. Sweeps: \"¡He probado todos los casinos para que tú no tengas que hacerlo. Aquí están los VERDADEROS ganadores!\"",
    "hero.title1": "Mejores Casinos",
    "hero.title2": "Sweepstakes EE.UU.",
    "hero.year": "2026",
    "hero.subtitle": "Juega legalmente. Reclama bonos. Gana premios reales.",
    "hero.noDeposit": "Sin depósito requerido",
    "hero.noDepositSuffix": " para empezar.",
    "hero.trust1": "Casinos revisados por expertos",
    "hero.trust2": "Actualizado diariamente",
    "hero.trust3": "Legal en 45+ estados",
    "hero.cta1": "Ver Mejores Casinos",
    "hero.cta2": "Cómo Funciona",
    "hero.stat1": "Casinos Revisados",
    "hero.stat2": "Estados Legales",
    "hero.stat3": "Gratis para Jugar",

    // ── Auth Modal ────────────────────────────────────────────────────────────
    "auth.loginTitle": "¡Bienvenido de Vuelta!",
    "auth.loginSubtitle": "Inicia sesión para guardar tus casinos favoritos y rastrear bonos.",
    "auth.signupTitle": "Únete a Sweeptakes.com",
    "auth.signupSubtitle": "Crea tu cuenta gratis y empieza a rastrear los mejores bonos.",
    "auth.loginWith": "Continuar con Manus",
    "auth.orEmail": "o continúa con tu correo",
    "auth.email": "Correo electrónico",
    "auth.password": "Contraseña",
    "auth.name": "Nombre completo",
    "auth.loginBtn": "Iniciar Sesión",
    "auth.signupBtn": "Crear Cuenta Gratis",
    "auth.noAccount": "¿No tienes cuenta?",
    "auth.hasAccount": "¿Ya tienes cuenta?",
    "auth.signupLink": "Regístrate gratis",
    "auth.loginLink": "Inicia sesión",
    "auth.forgotPassword": "¿Olvidaste tu contraseña?",
    "auth.terms": "Al crear una cuenta aceptas nuestros",
    "auth.termsLink": "Términos de Servicio",
    "auth.and": "y",
    "auth.privacyLink": "Política de Privacidad",
    "auth.loggedInAs": "Conectado como",
    "auth.logoutConfirm": "Has cerrado sesión.",

    // ── Bonus Ticker ──────────────────────────────────────────────────────────
    "ticker.label": "🔥 Bonos de Hoy",
    "ticker.item1": "🎰 Stake.us — 250K Monedas de Oro + 1 SC GRATIS",
    "ticker.item2": "⚡ RealPrize — 10,000 Monedas de Oro Sin Depósito",
    "ticker.item3": "👑 Crown Coins — 1,000 CC + 10 SC Bono de Bienvenida",
    "ticker.item4": "🎯 McLuck — 7,500 MO + 2.5 SC para Nuevos Jugadores",
    "ticker.item5": "🌟 WOW Vegas — 1.75 SC + 35 WOW Coins Gratis",
    "ticker.item6": "🤠 LoneStar — 5,000 Monedas de Oro al Registrarte",
    "ticker.item7": "💰 Fortuna — 500 FC + 5 SC Paquete de Bienvenida",
    "ticker.item8": "🎪 Hello Millions — 2M Hello Coins + 2 SC",

    // ── What Are Sweepstakes Casinos ──────────────────────────────────────────
    "what.badge": "Mr. Sweeps Explica",
    "what.title1": "¿Qué Son los Casinos",
    "what.title2": "Sweepstakes?",
    "what.desc": "Los casinos sweepstakes son una forma única y legal de juego en línea disponible en la mayoría de los estados de EE.UU. A diferencia de los casinos en línea tradicionales, operan bajo la ley de sorteos, lo que significa que puedes jugar gratis y ganar premios reales.",
    "what.f1title": "Sistema de Dos Monedas",
    "what.f1desc": "Juega con Monedas de Oro (diversión) o Sweep Coins (canjeables). Nunca tienes que comprar nada.",
    "what.f2title": "100% Legal en EE.UU.",
    "what.f2desc": "Los casinos sweepstakes operan bajo la ley federal de sorteos, sin licencia de juego requerida.",
    "what.f3title": "Entrada Gratuita Siempre Disponible",
    "what.f3desc": "Por ley, siempre puedes solicitar Sweep Coins gratis por correo. Sin compra necesaria.",
    "what.f4title": "Canjea por Premios Reales",
    "what.f4desc": "Las Sweep Coins acumuladas se pueden canjear por premios en efectivo, tarjetas de regalo o cripto.",
    "what.step1": "Regístrate gratis, sin tarjeta de crédito",
    "what.step2": "Recibe Sweep Coins gratis al registrarte",
    "what.step3": "Juega slots, juegos de mesa y más",
    "what.step4": "Canjea Sweep Coins por premios en efectivo",

    // ── Top Casinos ───────────────────────────────────────────────────────────
    "casinos.badge": "Clasificados por Expertos 2026",
    "casinos.title1": "Mejores Casinos",
    "casinos.title2": "Sweepstakes EE.UU.",
    "casinos.desc": "Cada casino ha sido probado personalmente, verificado por legalidad y clasificado por nuestro equipo editorial.",
    "casinos.mrSweeps": "\"¡Estas son mis selecciones personales, los he jugado todos!\"",
    "casinos.readReview": "Leer Reseña Completa",
    "casinos.viewAll": "Ver los 11 Casinos",
    // Casino taglines en español
    "casino.stake.tagline": "Mejor Casino Sweepstakes en General",
    "casino.stake.badge": "Elección del Editor",
    "casino.stake.pro1": "Enorme biblioteca de juegos (800+)",
    "casino.stake.pro2": "Bonos diarios de inicio de sesión",
    "casino.stake.pro3": "Canjes rápidos",
    "casino.realprice.tagline": "Mejor para Slots y Variedad",
    "casino.realprice.badge": "Mejor Valorado",
    "casino.realprice.pro1": "Títulos de slots exclusivos",
    "casino.realprice.pro2": "Sin compra necesaria",
    "casino.realprice.pro3": "Compatible con móvil",
    "casino.crown.tagline": "Mejor Bono de Bienvenida",
    "casino.crown.badge": "Mejor Bono",
    "casino.crown.pro1": "Oferta de bienvenida generosa",
    "casino.crown.pro2": "Juegos con crupier en vivo",
    "casino.crown.pro3": "Soporte 24/7",
    "casino.mcluck.tagline": "Mejor para Nuevos Jugadores",
    "casino.mcluck.badge": "Recomendado para Principiantes",
    "casino.mcluck.pro1": "Registro sencillo",
    "casino.mcluck.pro2": "Sin KYC para premios pequeños",
    "casino.mcluck.pro3": "Excelente app móvil",
    "casino.wow.tagline": "Mejor Experiencia de Casino Social",
    "casino.wow.badge": "Popular",
    "casino.wow.pro1": "Ambiente estilo Las Vegas",
    "casino.wow.pro2": "Torneos disponibles",
    "casino.wow.pro3": "Juego instantáneo",
    "casino.lonestar.tagline": "Mejor para Jugadores de Texas",
    "casino.lonestar.badge": "Selección Regional",
    "casino.lonestar.pro1": "Enfoque en Texas Hold'em",
    "casino.lonestar.pro2": "Ofertas específicas por estado",
    "casino.lonestar.pro3": "Torneos de póker",
    "casino.fortuna.tagline": "Mejor Proceso de Canje",
    "casino.fortuna.badge": "Pago Rápido",
    "casino.fortuna.pro1": "Canjes de efectivo rápidos",
    "casino.fortuna.pro2": "Múltiples métodos de pago",
    "casino.fortuna.pro3": "Términos transparentes",
    "casino.hello.tagline": "Mejor para Jackpots Progresivos",
    "casino.hello.badge": "Rey del Jackpot",
    "casino.hello.pro1": "Enormes fondos de jackpot",
    "casino.hello.pro2": "Monedas gratis diarias",
    "casino.hello.pro3": "Recompensas de lealtad",
    "casino.spree.tagline": "Mejor Sweepstakes Móvil",
    "casino.spree.badge": "Mejor en Móvil",
    "casino.spree.pro1": "App nativa iOS y Android",
    "casino.spree.pro2": "Juego fluido",
    "casino.spree.pro3": "Registro rápido",
    "casino.funrize.tagline": "Mejor para Jugadores Casuales",
    "casino.funrize.badge": "Selección Casual",
    "casino.funrize.pro1": "Juego sin presión",
    "casino.funrize.pro2": "Interfaz amigable",
    "casino.funrize.pro3": "Torneos divertidos",
    "casino.mega.tagline": "Mayor Frecuencia de Bonos",
    "casino.mega.badge": "Rey de Bonos",
    "casino.mega.pro1": "Bonos cada hora",
    "casino.mega.pro2": "Recompensas por referidos",
    "casino.mega.pro3": "Programa VIP",

    // ── How We Rank ───────────────────────────────────────────────────────────
    "rank.badge": "Nuestra Metodología",
    "rank.title1": "Cómo",
    "rank.title2": "Clasificamos",
    "rank.title3": "los Casinos",
    "rank.desc": "Nuestro equipo editorial aplica un sistema de puntuación riguroso y transparente. Cada casino se prueba en persona antes de recibir una calificación.",
    "rank.c1title": "Cumplimiento Legal",
    "rank.c1desc": "Verificamos que cada casino opere bajo la ley de sorteos válida y sea accesible en tu estado.",
    "rank.c2title": "Valor del Bono",
    "rank.c2desc": "Evaluamos las ofertas de bienvenida, bonos diarios y el valor real de las Sweep Coins gratuitas.",
    "rank.c3title": "Selección de Juegos",
    "rank.c3desc": "Calidad y cantidad de slots, juegos de mesa, crupier en vivo y juegos especiales.",
    "rank.c4title": "Velocidad de Canje",
    "rank.c4desc": "Qué tan rápido y fácil es convertir Sweep Coins en premios en efectivo reales.",
    "rank.c5title": "Experiencia de Usuario",
    "rank.c5desc": "Rendimiento móvil, velocidad del sitio, proceso de registro y calidad del soporte al cliente.",
    "rank.c6title": "Actualizaciones Continuas",
    "rank.c6desc": "Volvemos a probar y actualizar cada reseña mensualmente para garantizar la precisión.",
    "rank.promiseTitle": "Nuestra Promesa Editorial",
    "rank.promiseDesc": "Sweeptakes.com opera de forma independiente. No somos propiedad de ningún operador de casino. Nuestras clasificaciones se basan únicamente en el mérito editorial. Podemos ganar comisiones de afiliados, pero esto nunca influye en nuestras puntuaciones ni recomendaciones.",

    // ── Featured Review (Stake.us) ────────────────────────────────────────────
    "review.badge": "Reseña Destacada",
    "review.title": "Reseña de Stake.us",
    "review.updated": "Última actualización: Febrero 2026 · Revisado por James Hartley",
    "review.editorsChoice": "Elección del Editor",
    "review.overallScore": "Puntuación General",
    "review.prosLabel": "✓ Ventajas",
    "review.consLabel": "✗ Desventajas",
    "review.bonusBreakdown": "🎁 Desglose de Bonos",
    "review.bonusWelcome": "Bono de Bienvenida",
    "review.bonusDaily": "Bono Diario",
    "review.bonusReferral": "Bono por Referido",
    "review.scoreGame": "Selección de Juegos",
    "review.scoreBonus": "Valor del Bono",
    "review.scoreRedemption": "Canje",
    "review.scoreMobile": "Móvil",
    "review.scoreSupport": "Soporte",
    "review.scoreLegal": "Legal",
    "review.pro1": "La mayor biblioteca de juegos (800+ títulos)",
    "review.pro2": "Bonos diarios de inicio de sesión y promociones",
    "review.pro3": "Canjes rápidos y confiables",
    "review.pro4": "Excelente experiencia móvil",
    "review.pro5": "Términos y condiciones transparentes",
    "review.pro6": "Soporte al cliente 24/7",
    "review.con1": "No disponible en el estado de Washington",
    "review.con2": "Mínimo de canje de $100",
    "review.con3": "Sin sala de póker dedicada",
    "review.bonusWelcomeVal": "250,000 Monedas de Oro + 1 Sweep Coin",
    "review.bonusDailyVal": "Bono diario de hasta 10,000 MO",
    "review.bonusReferralVal": "Gana 1 SC por referido",
    "review.ctaRead": "Leer Reseña Completa",
    "review.ctaVisit": "Visitar Stake.us",

    // ── Bonus Guide ───────────────────────────────────────────────────────────
    "bonus.badge": "Guía de Monedas Gratis",
    "bonus.title1": "Bonos y",
    "bonus.title2": "Monedas Gratis",
    "bonus.desc": "Cada casino sweepstakes ofrece múltiples formas de ganar Sweep Coins gratis. Aquí está todo lo que necesitas saber para maximizar tus recompensas.",
    "bonus.mrSweepsTip": "\"¡SIEMPRE puedes obtener Sweep Coins gratis, incluso sin gastar un centavo. ¡Esa es la belleza de los sweepstakes!\"",
    "bonus.proTipLabel": "Consejo Pro de Mr. Sweeps",
    "bonus.proTip": "¡Regístrate en múltiples casinos sweepstakes para maximizar tu colección de monedas gratis! Cada plataforma ofrece su propio bono de bienvenida, y como todos son gratis para unirse, ¡no hay razón para no reclamarlos todos!",
    "bonus.viewTop": "Ver Mejores Casinos",
    "bonus.b1title": "Bono de Bienvenida",
    "bonus.b1desc": "Obtén Monedas de Oro y Sweep Coins gratis solo por registrarte. Sin depósito requerido.",
    "bonus.b1value": "Hasta 250K MO + 10 SC",
    "bonus.b2title": "Bono de Inicio de Sesión Diario",
    "bonus.b2desc": "Inicia sesión cada día para reclamar monedas gratis. Cuanto más larga sea tu racha, mayor será la recompensa.",
    "bonus.b2value": "Monedas gratis diarias",
    "bonus.b3title": "Entrada Gratuita por Correo",
    "bonus.b3desc": "Por ley, siempre puedes solicitar Sweep Coins gratis enviando una solicitud manuscrita por correo.",
    "bonus.b3value": "Siempre gratis por ley",
    "bonus.b4title": "Recompensas VIP y de Lealtad",
    "bonus.b4desc": "Gana puntos de lealtad mientras juegas. Los niveles más altos desbloquean bonos exclusivos y canjes más rápidos.",
    "bonus.b4value": "Beneficios exclusivos",
    "bonus.b5title": "Bonos de Recarga",
    "bonus.b5desc": "Compra paquetes de Monedas de Oro y recibe Sweep Coins adicionales encima, opcional, nunca requerido.",
    "bonus.b5value": "SC extra en compras",
    "bonus.b6title": "Bonos por Referidos",
    "bonus.b6desc": "Invita amigos y gana monedas gratis cuando se registren y jueguen.",
    "bonus.b6value": "Gana por cada referido",

    // ── Legal & States ────────────────────────────────────────────────────────
    "legal.badge": "Disponibilidad por Estado",
    "legal.title1": "Legal y",
    "legal.title2": "Disponibilidad",
    "legal.title3": "por Estado",
    "legal.desc": "Los casinos sweepstakes son legales en la mayoría de los estados de EE.UU. Aquí está lo que necesitas saber sobre tu estado.",
    "legal.whyLegal": "Por Qué Es Legal",
    "legal.l1title": "Ley Federal de Sorteos",
    "legal.l1desc": "Los casinos sweepstakes operan bajo 18 U.S.C. § 1302 y los estatutos estatales de sorteos, no bajo la ley de juego.",
    "legal.l2title": "Sin Compra Necesaria",
    "legal.l2desc": "La base de la legalidad: la entrada gratuita siempre debe estar disponible. Todos los operadores lo cumplen.",
    "legal.l3title": "Variaciones por Estado",
    "legal.l3desc": "Algunos estados tienen restricciones adicionales. Siempre verifica las reglas específicas de tu estado antes de jugar.",
    "legal.legendTitle": "Leyenda de Estado",
    "legal.legendAvailable": "Disponible — Juega libremente",
    "legal.legendRestricted": "Restringido — Solo algunos casinos",
    "legal.legendUnavailable": "No Disponible — Verifica leyes locales",
    "legal.statesTitle": "Disponibilidad por Estado",
    "legal.statesCount": "Estados Disponibles",
    "legal.disclaimer": "* La disponibilidad por estado puede variar según el operador. Siempre verifica con el casino específico antes de jugar. Esta información se actualiza regularmente pero no constituye asesoramiento legal.",

    // ── Trust Section ─────────────────────────────────────────────────────────
    "trust.stat1label": "Casinos Revisados",
    "trust.stat2label": "Experiencia en la Industria",
    "trust.stat3label": "Lectores Mensuales",
    "trust.stat4label": "Independencia Editorial",
    "trust.teamBadge": "Nuestro Equipo",
    "trust.teamTitle1": "Conoce al",
    "trust.teamTitle2": "Equipo",
    "trust.teamTitle3": "Editorial",
    "trust.jh.role": "Analista Principal de Casinos",
    "trust.jh.bio": "Más de 10 años revisando casinos en línea y plataformas sweepstakes en EE.UU.",
    "trust.sc.role": "Editora Legal y de Cumplimiento",
    "trust.sc.bio": "Exabogada de juegos especializada en ley de sorteos y regulaciones estatales.",
    "trust.mr.role": "Especialista en Bonos y Promociones",
    "trust.mr.bio": "Dedicado a encontrar y verificar las mejores ofertas de bonos en todas las plataformas.",
    "trust.ctaTitle1": "¿Listo para Encontrar tu",
    "trust.ctaTitle2": "Casino Perfecto?",
    "trust.ctaDesc": "Mr. Sweeps ha hecho toda la investigación. Explora nuestros casinos sweepstakes mejor clasificados y empieza a jugar gratis hoy, sin depósito requerido.",
    "trust.ctaBtn": "Ver Mejores Casinos",

    // ── FAQ ───────────────────────────────────────────────────────────────────
    "faq.badge": "Preguntas Frecuentes",
    "faq.title1": "Preguntas",
    "faq.title2": "Frecuentes",
    "faq.mrSweeps": "\"¿Tienes preguntas? ¡Tengo respuestas! Aquí está todo lo que necesitas saber.\"",
    "faq.cta": "Ver los Mejores Casinos Ahora",

    // ── Footer ────────────────────────────────────────────────────────────────
    "footer.tagline": "La guía de confianza para casinos sweepstakes legales en Estados Unidos.",
    "footer.editorial": "Independencia Editorial Garantizada",
    "footer.col1": "Mejores Casinos",
    "footer.col1.l1": "Reseña de Stake.us",
    "footer.col1.l2": "Reseña de RealPrize",
    "footer.col1.l3": "Reseña de Crown Coins",
    "footer.col1.l4": "Reseña de McLuck",
    "footer.col1.l5": "Reseña de WOW Vegas",
    "footer.col1.l6": "Todas las Reseñas",
    "footer.col2": "Guías",
    "footer.col2.l1": "¿Qué son los Casinos Sweepstakes?",
    "footer.col2.l2": "Cómo Reclamar Monedas Gratis",
    "footer.col2.l3": "Guía de Canje",
    "footer.col2.l4": "Bonos y Promociones",
    "footer.col2.l5": "Juego Responsable",
    "footer.col3": "Legal",
    "footer.col3.l1": "Disponibilidad por Estado",
    "footer.col3.l2": "Aviso Legal",
    "footer.col3.l3": "Política Editorial",
    "footer.col3.l4": "Política de Privacidad",
    "footer.col3.l5": "Términos de Servicio",
    "footer.col3.l6": "Contáctanos",
    "footer.col4": "Empresa",
    "footer.col4.l1": "Sobre Sweeptakes.com",
    "footer.col4.l2": "Nuestro Equipo Editorial",
    "footer.col4.l3": "Cómo Clasificamos Casinos",
    "footer.col4.l4": "Anúnciate con Nosotros",
    "footer.col4.l5": "Mapa del Sitio",
    "footer.responsible": "Juega Responsablemente",
    "footer.responsibleDesc": "Los casinos sweepstakes son solo para entretenimiento. Si sientes que tu juego se está volviendo problemático, visita",
    "footer.responsibleLink": "NCPG",
    "footer.responsibleSuffix": "o llama al 1-800-522-4700 para apoyo gratuito y confidencial.",
    "footer.responsibleBtn": "Más Información",
    "footer.disclaimer": "Aviso Legal: Sweeptakes.com es un sitio web editorial independiente. No somos un operador de casino ni ofrecemos servicios de juego. La información en este sitio es solo para fines informativos. Los casinos sweepstakes son legales en la mayoría de los estados de EE.UU. bajo la ley federal de sorteos. Podemos recibir compensación de los operadores de casino cuando haces clic en los enlaces de nuestro sitio, pero esto nunca influye en nuestras calificaciones ni recomendaciones editoriales. Siempre verifica el estado legal del juego sweepstakes en tu jurisdicción antes de participar. Debes tener 18+ años para jugar en casinos sweepstakes.",
    "footer.copyright": "© 2026 Sweeptakes.com. Todos los derechos reservados. No afiliado con ningún operador de casino.",
    "footer.privacy": "Privacidad",
    "footer.terms": "Términos",
    "footer.cookies": "Cookies",
    "footer.sitemap": "Mapa del Sitio",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const stored = localStorage.getItem("sweeptakes-lang");
    if (stored === "en" || stored === "es") return stored;
    // Auto-detect browser language — default to Spanish for US Latino audience
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith("es") ? "es" : "en";
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("sweeptakes-lang", newLang);
  };

  const t = (key: string): string => {
    return translations[lang][key] ?? translations["en"][key] ?? key;
  };

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
